In [106]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler, RobustScaler
import warnings
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import pickle
warnings.filterwarnings("ignore")

In [107]:
df = pd.read_csv("GameData.csv")
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
mapping = {'TRUE': 1, 'FALSE': 0}
columns_to_convert = ['has_round_started', 'is_round_over','player2_is_jumping', 'player2_is_crouching',
                        'player2_is_player_in_move','player1_is_jumping', 'player1_is_crouching', 'player1_is_player_in_move','player1_button_down', 'player1_button_right',
                        'player1_button_left', 'player1_button_select',
                        'player1_button_start', 'player1_button_Y',
                        'player1_button_B', 'player1_button_X',
                        'player1_button_A', 'player1_button_L',
                        'player1_button_R', 'player2_button_up',
                        'player2_button_down', 'player2_button_right',
                        'player2_button_left', 'player2_button_select',
                        'player2_button_start', 'player2_buttons.Y',
                        'player2_button_B', 'player2_button_X',
                        'player2_button_A', 'player2_button_L',
                        'player2_button_R']  # Replace with your column names
for column in columns_to_convert:
    df[column] = df[column].map(mapping)


In [108]:
for i in df.columns:
    print(i)
    print(df[i].head())
    print(df[i].dtype,'\n')

Timer
0    153
1    153
2    153
3    153
4    153
Name: Timer, dtype: int64
int64 

fight_result
0    NOT_OVER
1    NOT_OVER
2    NOT_OVER
3    NOT_OVER
4    NOT_OVER
Name: fight_result, dtype: object
object 

has_round_started
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: has_round_started, dtype: float64
float64 

is_round_over
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: is_round_over, dtype: float64
float64 

player1_id
0    0
1    0
2    0
3    0
4    0
Name: player1_id, dtype: int64
int64 

player1_health
0    176
1    176
2    176
3    176
4    176
Name: player1_health, dtype: int64
int64 

player1_x_coord
0    205
1    205
2    205
3    205
4    205
Name: player1_x_coord, dtype: int64
int64 

player1_y_coord
0    192
1    192
2    192
3    192
4    192
Name: player1_y_coord, dtype: int64
int64 

player1_is_jumping
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: player1_is_jumping, dtype: float64
float64 

player1_is_crouching
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: player

In [109]:
catagorical = []
for i in df.columns:
    if df[i].dtype == 'object' or df[i].dtype == 'bool':
        catagorical.append(i)

In [110]:
catagorical

['fight_result', 'player1_button_up']

In [111]:
keys = {'NOT_OVER': 0,
       'P1':1,
       'P2':2,
       True:1,
       False:0
       }

In [112]:
for i in catagorical:
    df[i]=df[i].map(keys)

In [113]:
df

Timer  fight_result  has_round_started  is_round_over  player1_id  \
0       153             0                NaN            NaN           0   
1       153             0                NaN            NaN           0   
2       153             0                NaN            NaN           0   
3       153             0                NaN            NaN           0   
4       153             0                NaN            NaN           0   
...     ...           ...                ...            ...         ...   
3428    132             0                NaN            NaN           0   
3429    132             0                NaN            NaN           0   
3430    132             0                NaN            NaN           0   
3431    132             0                NaN            NaN           0   
3432    132             2                NaN            NaN           0   

      player1_health  player1_x_coord  player1_y_coord  player1_is_jumping  \
0                176              205              192                 NaN   
1                176              205              192                 NaN   
2                176              205              192                 NaN   
3                176              205              192                 NaN   
4                176              205              192                 NaN   
...              ...              ...              ...                 ...   
3428              14               55              192                 NaN   
3429              14               55              192                 NaN   
3430              14               55              192                 NaN   
3431              14               55              192                 NaN   
3432             255               89              192                 NaN   

      player1_is_crouching  ...  player2_button_right  player2_button_left  \
0                      NaN  ...                   NaN                  NaN   
1                      NaN  ...                   NaN                  NaN   
2                      NaN  ...                   NaN                  NaN   
3                      NaN  ...                   NaN                  NaN   
4                      NaN  ...                   NaN                  NaN   
...                    ...  ...                   ...                  ...   
3428                   NaN  ...                   NaN                  NaN   
3429                   NaN  ...                   NaN                  NaN   
3430                   NaN  ...                   NaN                  NaN   
3431                   NaN  ...                   NaN                  NaN   
3432                   NaN  ...                   NaN                  NaN   

      player2_button_select  player2_button_start  player2_buttons.Y  \
0                       NaN                   NaN                NaN   
1                       NaN                   NaN                NaN   
2                       NaN                   NaN                NaN   
3                       NaN                   NaN                NaN   
4                       NaN                   NaN                NaN   
...                     ...                   ...                ...   
3428                    NaN                   NaN                NaN   
3429                    NaN                   NaN                NaN   
3430                    NaN                   NaN                NaN   
3431                    NaN                   NaN                NaN   
3432                    NaN                   NaN                NaN   

      player2_button_B  player2_button_X  player2_button_A  player2_button_L  \
0                  NaN               NaN               NaN               NaN   
1                  NaN               NaN               NaN               NaN   
2                  NaN               NaN               NaN               NaN   
3                  NaN               NaN      

In [114]:
for i in df.columns:
    if 'button' in i:
        print(i)

player1_button_up
player1_button_down
player1_button_right
player1_button_left
player1_button_select
player1_button_start
player1_button_Y
player1_button_B
player1_button_X
player1_button_A
player1_button_L
player1_button_R
player2_button_up
player2_button_down
player2_button_right
player2_button_left
player2_button_select
player2_button_start
player2_buttons.Y
player2_button_B
player2_button_X
player2_button_A
player2_button_L
player2_button_R


In [115]:
df = df.dropna()

In [116]:
X = df.drop(['player1_button_up','player1_button_down','player1_button_right','player1_button_left','player1_button_select','player1_button_start','player1_button_Y','player1_button_B','player1_button_X','player1_button_A','player1_button_L','player1_button_R'],axis=1)
Y = df[['player1_button_up','player1_button_down','player1_button_right','player1_button_left','player1_button_select','player1_button_start','player1_button_Y','player1_button_B','player1_button_X','player1_button_A','player1_button_L','player1_button_R']]

In [117]:
X

Empty DataFrame
Columns: [Timer, fight_result, has_round_started, is_round_over, player1_id, player1_health, player1_x_coord, player1_y_coord, player1_is_jumping, player1_is_crouching, player1_is_player_in_move, player1_move_id, player2_id, player2_health, player2_x_coord, player2_y_coord, player2_is_jumping, player2_is_crouching, player2_is_player_in_move, player2_move_id, player2_button_up, player2_button_down, player2_button_right, player2_button_left, player2_button_select, player2_button_start, player2_buttons.Y, player2_button_B, player2_button_X, player2_button_A, player2_button_L, player2_button_R]
Index: []

[0 rows x 32 columns]

In [118]:
X.isna().sum()

Timer                        0.0
fight_result                 0.0
has_round_started            0.0
is_round_over                0.0
player1_id                   0.0
player1_health               0.0
player1_x_coord              0.0
player1_y_coord              0.0
player1_is_jumping           0.0
player1_is_crouching         0.0
player1_is_player_in_move    0.0
player1_move_id              0.0
player2_id                   0.0
player2_health               0.0
player2_x_coord              0.0
player2_y_coord              0.0
player2_is_jumping           0.0
player2_is_crouching         0.0
player2_is_player_in_move    0.0
player2_move_id              0.0
player2_button_up            0.0
player2_button_down          0.0
player2_button_right         0.0
player2_button_left          0.0
player2_button_select        0.0
player2_button_start         0.0
player2_buttons.Y            0.0
player2_button_B             0.0
player2_button_X             0.0
player2_button_A             0.0
player2_bu

In [119]:
sc = StandardScaler()
rb = RobustScaler()
X = sc.fit_transform(X)
X = rb.fit_transform(X)

ValueError: Found array with 0 sample(s) (shape=(0, 32)) while a minimum of 1 is required by StandardScaler.

In [ ]:
X

array([[ 0.91428571,  0.        , -4.34132845, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.91428571,  0.        , -4.34132845, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.91428571,  0.        , -4.34132845, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.31428571,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.31428571,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.31428571, 32.51874429,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
Y

player1_button_up  player1_button_down  player1_button_right  \
0                     0                    0                     0   
1                     0                    0                     0   
2                     0                    0                     0   
3                     0                    1                     0   
4                     0                    0                     0   
...                 ...                  ...                   ...   
3428                  0                    1                     1   
3429                  0                    0                     0   
3430                  0                    0                     1   
3431                  0                    0                     0   
3432                  0                    0                     0   

      player1_button_left  player1_button_select  player1_button_start  \
0                       0                      0                     0   
1                       0                      0                     0   
2                       1                      0                     0   
3                       1                      0                     0   
4                       0                      0                     0   
...                   ...                    ...                   ...   
3428                    0                      0                     0   
3429                    0                      0                     0   
3430                    0                      0                     0   
3431                    0                      0                     0   
3432                    0                      0                     0   

      player1_button_Y  player1_button_B  player1_button_X  player1_button_A  \
0                    0                 0                 0                 0   
1                    0                 0                 0                 0   
2                    0                 0                 0                 0   
3                    0                 0                 0                 0   
4                    0                 0                 0                 0   
...                ...               ...               ...               ...   
3428                 0                 0                 0                 0   
3429                 0                 0                 0                 0   
3430                 1                 0                 0                 0   
3431                 0                 0                 0                 0   
3432                 0                 0                 0                 0   

      player1_button_L  player1_button_R  
0                    0                 0  
1                    0                 0  
2                    0                 0  
3                    0                 0  
4                    0                 0  
...                ...               ...  
3428                 0                 0  
3429                 0                 0  
3430                 0                 0  
3431                 0                 0  
3432                 0                 0  

[3433 rows x 12 columns]

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2)

In [ ]:
print(y_train.shape)

(2746, 12)


In [ ]:
reg = LinearRegression()
reg.fit(x_train, y_train)
y_pred = reg.predict(x_test)
y_pred = np.where(y_pred > 0.5,1,0)
print(f"loss is {mean_squared_error(y_test,y_pred)}")

loss is 0.06962639495390587


In [ ]:
print(y_pred)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
with open('Model.pkl', 'wb') as f:
    pickle.dump(reg, f)

In [ ]:
# Save the scaler objects and their arguments using pickle
with open('Scaler.pkl', 'wb') as f:
    pickle.dump(sc, f)
np.save('X_scaled_sc.npy', X)
with open('RobustScaler.pkl', 'wb') as f:
    pickle.dump(rb, f)
np.save('X_scaled_rb.npy', X)